version: "3.8"
services:
  app:
    container_name: nexus-news
    image: nexus-news
    build:
      target: development
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
